"""keep won_by nullable

Revision ID: 0d083aaeab29
Revises: c0e87c96a185
Create Date: 2025-08-29 09:14:09.404319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d083aaeab29'
down_revision: Union[str, Sequence[str], None] = 'c0e87c96a185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'captured_black')
    op.drop_column('game', 'captured_white')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('captured_white', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('captured_black', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
