"""remove nickname column

Revision ID: c0e87c96a185
Revises: d08309cb0a7f
Create Date: 2025-08-27 21:53:02.834298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e87c96a185'
down_revision: Union[str, Sequence[str], None] = 'd08309cb0a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'nick_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('nick_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
