from app import Base

from sqlalchemy import Column,JSON,BIGINT,DateTime,func,ForeignKey,Boolean,String

#1:1 -> unique 

class Game(Base):

    __tablename__="game"

    id = Column(BIGINT, primary_key=True, autoincrement=True)

    # Two players per game
    black_player_id = Column(BIGINT, ForeignKey("player.id"), nullable=False)
    white_player_id = Column(BIGINT, ForeignKey("player.id"), nullable=False)

    board = Column(JSON, nullable=False)
    # captured_black = Column(BIGINT, default=0)
    # captured_white = Column(BIGINT, default=0)
    won_by = Column(String, nullable=True)
    #Auto generated By The DB
    created_at=Column(DateTime(timezone=True),server_default=func.now())